# Generated by Django 4.0 on 2022-01-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_site', '0002_rename_street_restaurant_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
