# Generated by Django 4.0 on 2022-01-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_site', '0004_alter_restaurant_image_alter_restaurant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='country',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='google_maps_embed_link',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='street_address',
            field=models.CharField(max_length=512),
        ),
    ]
