# Generated by Django 4.0 on 2022-01-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_site', '0005_alter_restaurant_city_alter_restaurant_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='google_maps_embed_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
